--liquibase formatted sql

--changeset andrey:1
DROP TABLE IF EXISTS `PATIENTS`;
CREATE TABLE `PATIENTS` (
  `PATIENT_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `PHONE` VARCHAR(50) NOT NULL,
  `STATEID` INT(11) NOT NULL,
  PRIMARY KEY (`PATIENT_ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
--rollback drop table PATIENTS;

--changeset andrey:2
DROP TABLE IF EXISTS `STATES`;
CREATE TABLE `STATES` (
  `STATE_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `CODE` VARCHAR(50) NOT NULL,
  `NAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`STATE_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--rollback drop table STATES;

--changeset andrey:3
DROP TABLE IF EXISTS `PRODUCTS`;
CREATE TABLE `PRODUCTS` (
  `PRODUCT_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `STATEID` INT(11) NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--rollback drop table PRODUCTS;

--changeset andrey:4
DROP TABLE IF EXISTS `TRANSACTIONS`;
CREATE TABLE `TRANSACTIONS` (
  `TRANSACTION_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `PATIENTID` INT(11) NOT NULL,
  `PRODUCTID` INT(11) NOT NULL,
  `DATE_TRANSACTION` DATE NOT NULL,
  PRIMARY KEY (`TRANSACTION_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--rollback drop table TRANSACTIONS;

--changeset andrey:5
DROP TABLE IF EXISTS `AUDITOPERATIONS`;
CREATE TABLE `AUDITOPERATIONS` (
  `AUDIT_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DATE_AUDIT` DATE NOT NULL,
  `STATUS` VARCHAR(30) NOT NULL,
  `ACTION` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`AUDIT_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--rollback drop table AUDITOPERATIONS;